/**************************************************************************/
/* Copyright (c) 2020 Qualcomm Technologies International, Ltd.           */
/* Autogenerated File, Do Not Edit                                        */
/*                                                                        */
/* This file exports public entry points from patch code                  */
/*                                                                        */
/**************************************************************************/
#ifndef SUBSYS3_PATCH0_FW00001BD0_MAP_PUBLIC_H
#define SUBSYS3_PATCH0_FW00001BD0_MAP_PUBLIC_H

#define PATCH_BUILD_ID                           12417

#define ENTRY_POINT_TTP_CONFIGURE_SP_ADJUSTMENT  0x04002407 /* $_ttp_configure_sp_adjustment */
#define ENTRY_POINT_TTP_ADJUST_TTP_TIMESTAMP     0x04002419 /* $_ttp_adjust_ttp_timestamp */
#define ENTRY_POINT_TTP_GET_MSG_STATE_PARAMS     0x04002431 /* $_ttp_get_msg_state_params */
#define ENTRY_POINT_TTP_CONFIGURE_STATE_PARAMS   0x04002481 /* $_ttp_configure_state_params */
#define ENTRY_POINT_TTP_GET_STATE_PARAMS_STATUS  0x0400252d /* $_ttp_get_state_params_status */
#define ENTRY_POINT_GET_MSG_SP_ADJUSTMENT        0x040023eb /* $_ttp_get_msg_sp_adjustment */
#define ENTRY_POINT_TTP_GET_MSG_ADJUST_TTP_TIMESTAMP 0x040023f9 /* $_ttp_get_msg_adjust_ttp_timestamp */
#define ENTRY_POINT_THREAD_OFFLOAD_UPDATE_P1_MEM_LOCATION 0x040027e3 /* $_thread_offload_update_p1_mem_location */
#define ENTRY_POINT_STREAM_SHORT_DOWNSTREAM_PROBE 0x0400484b /* $_stream_short_downstream_probe */
#define ENTRY_POINT_STREAM_CALC_DOWNSTREAM_AMOUNT_WORDS_EX 0x040048c3 /* $_stream_calc_downstream_amount_words_ex */
#define ENTRY_POINT_STREAM_TRANSFORM_FROM_BUFFER 0x04004901 /* $_stream_transform_from_buffer */
#define ENTRY_POINT_CREATE_HOWLING_LIMITER_OP_PATCH 0x04005aaf /* $_create_howling_limiter_op_patch */
#define ENTRY_POINT_INITIALIZE_HOWLING_LIMITER_OP_PATCH 0x04005aeb /* $_initialize_howling_limiter_op_patch */
#define ENTRY_POINT_CONFIGURE_HOWLING_LIMITER_OP_PATCH 0x04005af5 /* $_configure_howling_limiter_op_patch */

#endif /* SUBSYS3_PATCH0_FW00001BD0_MAP_PUBLIC_H */
