/*****************************************************************************
Copyright (c) 2018 - 2020 Qualcomm Technologies International, Ltd.
******************************************************************************/

/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: firmware.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "firmware.pb-c.h"
void   firmware_component__init
                     (FirmwareComponent         *message)
{
  static const FirmwareComponent init_value = FIRMWARE_COMPONENT__INIT;
  *message = init_value;
}
size_t firmware_component__get_packed_size
                     (const FirmwareComponent *message)
{
  assert(message->base.descriptor == &firmware_component__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t firmware_component__pack
                     (const FirmwareComponent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &firmware_component__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t firmware_component__pack_to_buffer
                     (const FirmwareComponent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &firmware_component__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FirmwareComponent *
       firmware_component__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FirmwareComponent *)
     protobuf_c_message_unpack (&firmware_component__descriptor,
                                allocator, len, data);
}
void   firmware_component__free_unpacked
                     (FirmwareComponent *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &firmware_component__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   firmware_information__init
                     (FirmwareInformation         *message)
{
  static const FirmwareInformation init_value = FIRMWARE_INFORMATION__INIT;
  *message = init_value;
}
size_t firmware_information__get_packed_size
                     (const FirmwareInformation *message)
{
  assert(message->base.descriptor == &firmware_information__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t firmware_information__pack
                     (const FirmwareInformation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &firmware_information__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t firmware_information__pack_to_buffer
                     (const FirmwareInformation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &firmware_information__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FirmwareInformation *
       firmware_information__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FirmwareInformation *)
     protobuf_c_message_unpack (&firmware_information__descriptor,
                                allocator, len, data);
}
void   firmware_information__free_unpacked
                     (FirmwareInformation *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &firmware_information__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   get_firmware_information__init
                     (GetFirmwareInformation         *message)
{
  static const GetFirmwareInformation init_value = GET_FIRMWARE_INFORMATION__INIT;
  *message = init_value;
}
size_t get_firmware_information__get_packed_size
                     (const GetFirmwareInformation *message)
{
  assert(message->base.descriptor == &get_firmware_information__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t get_firmware_information__pack
                     (const GetFirmwareInformation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &get_firmware_information__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t get_firmware_information__pack_to_buffer
                     (const GetFirmwareInformation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &get_firmware_information__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GetFirmwareInformation *
       get_firmware_information__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GetFirmwareInformation *)
     protobuf_c_message_unpack (&get_firmware_information__descriptor,
                                allocator, len, data);
}
void   get_firmware_information__free_unpacked
                     (GetFirmwareInformation *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &get_firmware_information__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor firmware_component__field_descriptors[4] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(FirmwareComponent, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(FirmwareComponent, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(FirmwareComponent, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(FirmwareComponent, signature),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned firmware_component__field_indices_by_name[] = {
  1,   /* field[1] = name */
  3,   /* field[3] = signature */
  2,   /* field[2] = size */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange firmware_component__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor firmware_component__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FirmwareComponent",
  "FirmwareComponent",
  "FirmwareComponent",
  "",
  sizeof(FirmwareComponent),
  4,
  firmware_component__field_descriptors,
  firmware_component__field_indices_by_name,
  1,  firmware_component__number_ranges,
  (ProtobufCMessageInit) firmware_component__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor firmware_information__field_descriptors[6] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(FirmwareInformation, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(FirmwareInformation, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "components",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(FirmwareInformation, n_components),
    offsetof(FirmwareInformation, components),
    &firmware_component__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "locale",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(FirmwareInformation, locale),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version_name",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(FirmwareInformation, version_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_id",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(FirmwareInformation, device_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned firmware_information__field_indices_by_name[] = {
  2,   /* field[2] = components */
  5,   /* field[5] = device_id */
  3,   /* field[3] = locale */
  1,   /* field[1] = name */
  0,   /* field[0] = version */
  4,   /* field[4] = version_name */
};
static const ProtobufCIntRange firmware_information__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor firmware_information__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FirmwareInformation",
  "FirmwareInformation",
  "FirmwareInformation",
  "",
  sizeof(FirmwareInformation),
  6,
  firmware_information__field_descriptors,
  firmware_information__field_indices_by_name,
  1,  firmware_information__number_ranges,
  (ProtobufCMessageInit) firmware_information__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor get_firmware_information__field_descriptors[1] =
{
  {
    "device_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GetFirmwareInformation, device_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned get_firmware_information__field_indices_by_name[] = {
  0,   /* field[0] = device_id */
};
static const ProtobufCIntRange get_firmware_information__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor get_firmware_information__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GetFirmwareInformation",
  "GetFirmwareInformation",
  "GetFirmwareInformation",
  "",
  sizeof(GetFirmwareInformation),
  1,
  get_firmware_information__field_descriptors,
  get_firmware_information__field_indices_by_name,
  1,  get_firmware_information__number_ranges,
  (ProtobufCMessageInit) get_firmware_information__init,
  NULL,NULL,NULL    /* reserved[123] */
};
