@startuml

    object OPR_ADD_HEADROOM
    OPR_ADD_HEADROOM : id = CAP_ID_BASIC_PASS
    object OPR_SPEAKER_EQ
    OPR_SPEAKER_EQ : id = CAP_ID_PEQ
    object OPR_REMOVE_HEADROOM
    OPR_REMOVE_HEADROOM : id = CAP_ID_BASIC_PASS
    OPR_SPEAKER_EQ "IN(0)"<-- "OUT(0)" OPR_ADD_HEADROOM
    OPR_REMOVE_HEADROOM "IN(0)"<-- "OUT(0)" OPR_SPEAKER_EQ
    object EPR_MUSIC_PROCESSING_IN_L #lightgreen
    OPR_ADD_HEADROOM "IN(0)" <-- EPR_MUSIC_PROCESSING_IN_L
    object EPR_MUSIC_PROCESSING_OUT_L #lightblue
    EPR_MUSIC_PROCESSING_OUT_L <-- "OUT(0)" OPR_REMOVE_HEADROOM
@enduml
