@startuml

    object OPR_RESAMPLER
    OPR_RESAMPLER : id = CAP_ID_IIR_RESAMPLER
    object EPR_MIC_RESAMPLER_IN_REF #lightgreen
    OPR_RESAMPLER "IN_REF(0)" <-- EPR_MIC_RESAMPLER_IN_REF
    object EPR_MIC_RESAMPLER_IN1 #lightgreen
    OPR_RESAMPLER "IN1(1)" <-- EPR_MIC_RESAMPLER_IN1
    object EPR_MIC_RESAMPLER_IN2 #lightgreen
    OPR_RESAMPLER "IN2(2)" <-- EPR_MIC_RESAMPLER_IN2
    object EPR_MIC_RESAMPLER_IN3 #lightgreen
    OPR_RESAMPLER "IN3(3)" <-- EPR_MIC_RESAMPLER_IN3
    object EPR_MIC_RESAMPLER_OUT_REF #lightblue
    EPR_MIC_RESAMPLER_OUT_REF <-- "OUT_REF(0)" OPR_RESAMPLER
    object EPR_MIC_RESAMPLER_OUT1 #lightblue
    EPR_MIC_RESAMPLER_OUT1 <-- "OUT1(1)" OPR_RESAMPLER
    object EPR_MIC_RESAMPLER_OUT2 #lightblue
    EPR_MIC_RESAMPLER_OUT2 <-- "OUT2(2)" OPR_RESAMPLER
    object EPR_MIC_RESAMPLER_OUT3 #lightblue
    EPR_MIC_RESAMPLER_OUT3 <-- "OUT3(3)" OPR_RESAMPLER
@enduml
