@startuml

    object OPR_AANC_SPLT_SCO_TX
    OPR_AANC_SPLT_SCO_TX : id = CAP_ID_SPLITTER
    object OPR_AANC_BASIC_PASS
    OPR_AANC_BASIC_PASS : id = CAP_ID_BASIC_PASS
    OPR_AANC_SPLT_SCO_TX "IN(0)"<-- "OUT(0)" OPR_AANC_BASIC_PASS
    object EPR_AANC_BASIC_PASS_IN #lightgreen
    OPR_AANC_BASIC_PASS "IN(0)" <-- EPR_AANC_BASIC_PASS_IN
    object EPR_SPLT_OUT_CVC_SEND #lightblue
    EPR_SPLT_OUT_CVC_SEND <-- "OUT1(0)" OPR_AANC_SPLT_SCO_TX
    object EPR_SPLT_OUT_ANC_FF #lightblue
    EPR_SPLT_OUT_ANC_FF <-- "OUT2(1)" OPR_AANC_SPLT_SCO_TX
@enduml
