@startuml

    object OPR_AANC_CONSUMER
    OPR_AANC_CONSUMER : id = EB_CAP_ID_SWITCHED_PASSTHROUGH
    object EPR_AANC_CONSUMER #lightgreen
    OPR_AANC_CONSUMER "AEC_MIC_OUT_CONSUMER_IN(0)" <-- EPR_AANC_CONSUMER
@enduml
