/*!
\copyright  Copyright (c) 2017 - 2020 Qualcomm Technologies International, Ltd.\n
            All Rights Reserved.\n
            Qualcomm Technologies International, Ltd. Confidential and Proprietary.
\file
\brief      Definitions of audio capability IDs
*/

#ifndef EARBUD_CAP_IDS_H
#define EARBUD_CAP_IDS_H


#ifdef INCLUDE_GAA
#include <gaa_cap_ids.h>
#endif

#ifdef INCLUDE_AMA
#include <ama_cap_ids.h>
#endif

#if defined(__QCC3400_APP__) || defined(__QCC514X_APPS__)
#define DOWNLOAD_APTX_ADAPTIVE_DECODE
#define DOWNLOAD_SWITCHED_PASSTHROUGH
#ifdef ENABLE_ADAPTIVE_ANC
#define DOWNLOAD_ADAPTIVE_ANC
#endif
#elif defined(HAVE_STR_ROM_2_0_1)
/* QCC512X 2.1 ROM specific defines here */
#elif defined(__QCC302X_APPS__) || defined(__QCC512X_APPS__)
#define DOWNLOAD_SWITCHED_PASSTHROUGH
#define DOWNLOAD_APTX_CLASSIC_DEMUX
#define DOWNLOAD_AEC_REF
#define DOWNLOAD_ASYNC_WBS_DEC
#define DOWNLOAD_ASYNC_WBS_ENC
#endif

#if defined(__QCC3400_APP__) || defined(__QCC514X_APPS__) || defined(__QCC302X_APPS__) || defined(__QCC512X_APPS__)
#define DOWNLOAD_CVC_FBC
#endif


#ifdef KYMERA_SCO_USE_3MIC
#define DOWNLOAD_CVC_3MIC
#endif

#ifdef DOWNLOAD_AAC_DECODER
#define EB_CAP_ID_AAC_DECODER CAP_ID_DOWNLOAD_AAC_DECODER
#else
#define EB_CAP_ID_AAC_DECODER CAP_ID_AAC_DECODER
#endif

#ifdef DOWNLOAD_SWITCHED_PASSTHROUGH
#define EB_CAP_ID_SWITCHED_PASSTHROUGH   CAP_ID_DOWNLOAD_SWITCHED_PASSTHROUGH_CONSUMER
#else
#define EB_CAP_ID_SWITCHED_PASSTHROUGH   CAP_ID_SWITCHED_PASSTHROUGH_CONSUMER
#endif

#ifdef DOWNLOAD_APTX_CLASSIC_DEMUX
#define EB_CAP_ID_APTX_CLASSIC_DEMUX     CAP_ID_DOWNLOAD_APTX_CLASSIC_DEMUX
#else
#define EB_CAP_ID_APTX_CLASSIC_DEMUX     CAP_ID_APTX_CLASSIC_DEMUX
#endif

#ifdef DOWNLOAD_AEC_REF
#define EB_CAP_ID_AEC_REF                CAP_ID_DOWNLOAD_AEC_REFERENCE
#else
#define EB_CAP_ID_AEC_REF                CAP_ID_AEC_REFERENCE
#endif

#ifdef DOWNLOAD_ADAPTIVE_ANC
#define EB_CAP_ID_ADAPTIVE_ANC_REF       0x409F
#else
//#define EB_CAP_ID_ADAPTIVE_ANC_REF       CAP_ID_ADAPTIVE_ANC_REFERENCE
#define EB_CAP_ID_ADAPTIVE_ANC_REF       0x00C7
#endif

#ifdef DOWNLOAD_APTX_ADAPTIVE_DECODE
#define EB_CAP_ID_APTX_ADAPTIVE_DECODE   CAP_ID_DOWNLOAD_APTX_ADAPTIVE_DECODE
#else
#define EB_CAP_ID_APTX_ADAPTIVE_DECODE   CAP_ID_APTX_ADAPTIVE_DECODE
#endif

#ifdef DOWNLOAD_ASYNC_WBS_DEC
#define EB_CAP_ID_ASYNC_WBS_DEC          CAP_ID_DOWNLOAD_ASYNC_WBS_DEC
#else
#define EB_CAP_ID_ASYNC_WBS_DEC          CAP_ID_ASYNC_WBS_DEC
#endif

#ifdef DOWNLOAD_ASYNC_WBS_ENC
#define EB_CAP_ID_ASYNC_WBS_ENC          CAP_ID_DOWNLOAD_ASYNC_WBS_ENC
#else
#define EB_CAP_ID_ASYNC_WBS_ENC          CAP_ID_ASYNC_WBS_ENC
#endif

#ifdef DOWNLOAD_VOLUME_CONTROL
#define EB_CAP_ID_VOL_CTRL_VOL                CAP_ID_DOWNLOAD_VOL_CTRL_VOL
#else
#define EB_CAP_ID_VOL_CTRL_VOL                CAP_ID_VOL_CTRL_VOL
#endif

#ifdef DOWNLOAD_OPUS_CELT_ENCODE
#define EB_CAP_ID_OPUS_ENC          CAP_ID_DOWNLOAD_OPUS_CELT_ENCODE
#else
#define EB_CAP_ID_OPUS_ENC          CAP_ID_OPUS_CELT_ENCODE
#endif

#ifdef DOWNLOAD_VA_GRAPH_MANAGER
#define EB_CAP_ID_VA_GRAPH_MANAGER CAP_ID_DOWNLOAD_VA_GRAPH_MANAGER
#else
#define EB_CAP_ID_VA_GRAPH_MANAGER CAP_ID_VA_GRAPH_MANAGER
#endif

#ifdef DOWNLOAD_CVC_FBC
#define EB_CAP_ID_CVC_FBC CAP_ID_DOWNLOAD_CVC_FBC
#else
#define EB_CAP_ID_CVC_FBC CAP_ID_CVC_FBC
#endif

#ifdef DOWNLOAD_CVC_3MIC
#define EB_CAP_ID_CVC_3MIC_NB  0x40A5 //CAP_ID_DOWNLOAD_CVCEB3MIC_MONO_IE_NB
#define EB_CAP_ID_CVC_3MIC_WB  0x40A5 //CAP_ID_DOWNLOAD_CVCEB3MIC_MONO_IE_WB
#define EB_CAP_ID_CVC_3MIC_SWB 0x40A5 //CAP_ID_DOWNLOAD_CVCEB3MIC_MONO_IE_SWB
#else
#define EB_CAP_ID_CVC_3MIC_NB  0x83 //CAP_ID_CVCEB3MIC_MONO_IE_NB
#define EB_CAP_ID_CVC_3MIC_WB  0x83 //CAP_ID_CVCEB3MIC_MONO_IE_WB
#define EB_CAP_ID_CVC_3MIC_SWB 0x83 //CAP_ID_CVCEB3MIC_MONO_IE_SWB
#endif

#define EB_CAP_ID_CVC_VA_1MIC EB_CAP_ID_CVC_FBC

#if defined(__QCC3400_APP__) || defined(__QCC514X_APPS__)
#define EB_CAP_ID_CVC_VA_2MIC CAP_ID_CVCHS2MIC_BARGEIN_WB
#else
#define EB_CAP_ID_CVC_VA_2MIC CAP_ID_CVCHS2MIC_MONO_SEND_WB
#endif

#ifdef DOWNLOAD_GVA
#define EB_CAP_ID_GVA CAP_ID_DOWNLOAD_GVA
#else
/* This capability, if present, is always a downloadable */
#define EB_CAP_ID_GVA CAP_ID_NONE
#endif

#ifdef DOWNLOAD_APVA
#define EB_CAP_ID_APVA CAP_ID_DOWNLOAD_APVA
#else
/* This capability, if present, is always a downloadable */
#define EB_CAP_ID_APVA CAP_ID_NONE
#endif

#endif // EARBUD_CAP_IDS_H
